// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Role         sql.NullString
	CreatedAt    sql.NullTime
}
